steps:
  # Step 1: Build Docker Image for Container 2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/b00988337-w25-k8s/container2', '.']

  # Step 2: Push Docker Image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/b00988337-w25-k8s/container2']

  # Step 3: Deploy Container 2 to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', '/workspace/hetpatel.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'
